# -*- coding: utf-8 -*-
"""group7_general physics group project code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLXFD_LYIFu_jkxXFpynfml4EqQxPYz5
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML, display

# ============================================================
# 1. 논문 기반 시뮬레이션 파라미터
# ============================================================

g = 9.8                  # 중력가속도 (m/s^2)

R = 0.0215               # 공 반지름 (m), 슈퍼볼 약 2.15 cm
K = 2 / 5                # 균일한 구의 관성모멘트 계수 I = KmR^2

v0 = 0.25                # 초기 속도 (m/s)
theta0 = 0.0             # 초기 진행 방향 각도 (rad)

mu_k = 0.314             # 운동 마찰계수, 슈퍼볼 + high-pile carpet
D = 0.0093               # 운동 마찰력 작용점의 앞쪽 이동 거리 (m)
Ds = 0.0016              # 수직항력 작용점의 앞쪽 이동 거리 (m)

spin_frequency = 18      # 공의 수직축 회전수 (Hz), 논문에서 대략 15~20 Hz 사용

# ============================================================
# 2. 논문 모델 계산
# ============================================================

# b = Ds*g / (v0*R*(1+K))
b = Ds * g / (v0 * R * (1 + K))

# 공이 멈추는 시간
t_stop = 1 / b

# 시간 배열
num_frames = 300
t = np.linspace(0, 0.98 * t_stop, num_frames)

# 속도 v(t)
v = v0 * (1 - b * t)

# x(t) = 거의 이동거리 s(t)
x = v0 * t - (Ds * g / (2 * R * (1 + K))) * t**2

# y(t), 논문 Eq. (29) 기반
term1 = b * t * (b * t - 2)
term2 = 1 - (4 * R * Ds * theta0) / (mu_k * D**2)
term3 = -2 * (1 - b * t)**2 * np.log(1 - b * t)

y = (mu_k * D**2 * v0 / (8 * b * R * Ds)) * (term1 * term2 + term3)

# 진행 방향 각도 theta(t)
theta = theta0 - (mu_k * D**2 / (2 * R * Ds)) * np.log(1 - b * t)

# 공의 수직축 회전 각도
# 실제 논문에서는 공이 멈춘 뒤에도 회전이 남아 있다고 했지만,
# 여기서는 시각화를 위해 회전수가 서서히 줄어드는 형태로 표현함.
spin_angle = 2 * np.pi * spin_frequency * t * (1 - 0.3 * t / t_stop)

# ============================================================
# 3. 애니메이션 화면 설정
# ============================================================

fig, ax = plt.subplots(figsize=(8, 5))

margin = 0.04
ax.set_xlim(np.min(x) - margin, np.max(x) + margin)
ax.set_ylim(np.min(y) - margin, np.max(y) + margin)

ax.set_aspect("equal", adjustable="box")
ax.set_xlabel("x position (m)")
ax.set_ylabel("y drift position (m)")
ax.set_title("Virtual simulation: drift motion of a spinning ball on carpet")
ax.grid(True)

# 카펫 느낌의 배경: 옅은 격자선 추가
for yy in np.linspace(np.min(y) - margin, np.max(y) + margin, 20):
    ax.plot([np.min(x) - margin, np.max(x) + margin], [yy, yy], linewidth=0.3, alpha=0.25)

# 궤적 선
trail, = ax.plot([], [], linewidth=2, label="trajectory")

# 공
ball, = ax.plot([], [], "o", markersize=18, label="ball")

# 공 위의 회전 표시선
spin_line, = ax.plot([], [], linewidth=2)

# 현재 속도 방향 화살표
velocity_arrow = ax.arrow(0, 0, 0, 0)

# 텍스트 정보
info_text = ax.text(
    0.02, 0.96, "",
    transform=ax.transAxes,
    verticalalignment="top",
    fontsize=10,
    bbox=dict(boxstyle="round", facecolor="white", alpha=0.8)
)

ax.legend(loc="lower right")

# ============================================================
# 4. 애니메이션 업데이트 함수
# ============================================================

def update(frame):
    global velocity_arrow

    # 현재 공 위치
    bx = x[frame]
    by = y[frame]

    # 궤적 업데이트
    trail.set_data(x[:frame+1], y[:frame+1])

    # 공 위치 업데이트
    ball.set_data([bx], [by])

    # 공 위 회전 표시선
    # 실제 공 크기는 너무 작으므로 보기 좋게 시각화 반지름을 확대
    visual_R = 0.012
    angle = spin_angle[frame]

    x1 = bx - visual_R * np.cos(angle)
    y1 = by - visual_R * np.sin(angle)
    x2 = bx + visual_R * np.cos(angle)
    y2 = by + visual_R * np.sin(angle)

    spin_line.set_data([x1, x2], [y1, y2])

    # 기존 속도 화살표 제거
    velocity_arrow.remove()

    # 속도 방향 화살표 새로 그림
    arrow_length = 0.025
    dx = arrow_length * np.cos(theta[frame])
    dy = arrow_length * np.sin(theta[frame])

    velocity_arrow = ax.arrow(
        bx, by, dx, dy,
        head_width=0.006,
        head_length=0.008,
        length_includes_head=True
    )

    # 정보 텍스트
    info_text.set_text(
        f"time = {t[frame]:.2f} s\n"
        f"speed = {v[frame]:.3f} m/s\n"
        f"x = {x[frame]:.3f} m\n"
        f"y drift = {y[frame]:.3f} m\n"
        f"theta = {theta[frame]:.3f} rad"
    )

    return trail, ball, spin_line, info_text, velocity_arrow

# ============================================================
# 5. 애니메이션 생성 및 Colab에 표시
# ============================================================

ani = FuncAnimation(
    fig,
    update,
    frames=num_frames,
    interval=30,
    blit=False
)

plt.close(fig)

display(HTML(ani.to_jshtml()))

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

# ============================================================
# 1. 실험 파라미터 설정
# ============================================================

g = 9.8                      # 중력가속도 (m/s^2)

R = 0.0215                   # 공의 반지름 (m), 슈퍼볼 약 2.15 cm
K = 2 / 5                    # 균일한 꽉 찬 구의 관성모멘트 계수 I = KmR^2

v0 = 0.25                    # 초기 속도 (m/s)
theta0 = 0.0                 # 초기 진행 방향 각도 (rad)

mu_k = 0.314                 # 운동 마찰계수, 슈퍼볼 + high-pile carpet 근사값
D = 0.0093                   # 운동 마찰력의 앞쪽 이동 거리 (m)
Ds = 0.0016                  # 수직항력의 앞쪽 이동 거리 (m)

# ============================================================
# 2. 논문 모델에 필요한 값 계산
# ============================================================

# b = Ds*g / (v0*R*(1+K))
b = Ds * g / (v0 * R * (1 + K))

# 공이 멈추는 시간: v(t)=0이 되는 시간
t_stop = 1 / b

# 로그 안쪽이 0이 되면 계산 문제가 생기므로 t_stop보다 약간 짧게 계산
t = np.linspace(0, 0.99 * t_stop, 500)

# 속도 v(t)
v = v0 * (1 - b * t)

# x(t) = 이동거리 s(t)
x = v0 * t - (Ds * g / (2 * R * (1 + K))) * t**2

# y(t): 논문 Eq. (29)에 해당하는 식
term1 = b * t * (b * t - 2)
term2 = 1 - (4 * R * Ds * theta0) / (mu_k * D**2)
term3 = -2 * (1 - b * t)**2 * np.log(1 - b * t)

y = (mu_k * D**2 * v0 / (8 * b * R * Ds)) * (term1 * term2 + term3)

# 진행 방향 각도 theta(t)
theta = theta0 - (mu_k * D**2 / (2 * R * Ds)) * np.log(1 - b * t)

# ============================================================
# 3. 기본 결과 출력
# ============================================================

print("===== Simulation Parameters =====")
print(f"R = {R:.4f} m")
print(f"K = {K:.3f}")
print(f"v0 = {v0:.3f} m/s")
print(f"mu_k = {mu_k:.3f}")
print(f"D = {D*1000:.2f} mm")
print(f"Ds = {Ds*1000:.2f} mm")
print(f"b = {b:.3f} 1/s")
print(f"t_stop = {t_stop:.3f} s")
print(f"maximum x = {x[-1]:.3f} m")
print(f"maximum y = {y[-1]:.3f} m")

# ============================================================
# 4. 그래프 1: 공의 xy 궤적
# ============================================================

plt.figure(figsize=(7, 5))
plt.plot(x, y, linewidth=2)
plt.scatter(x[0], y[0], label="start")
plt.scatter(x[-1], y[-1], label="near stop")
plt.xlabel("x position (m)")
plt.ylabel("y drift position (m)")
plt.title("Simulated drift trajectory of a spinning ball on carpet")
plt.axis("equal")
plt.grid(True)
plt.legend()
plt.show()

# ============================================================
# 5. 그래프 2: 시간에 따른 y 드리프트
# ============================================================

plt.figure(figsize=(7, 5))
plt.plot(t, y, linewidth=2)
plt.xlabel("time (s)")
plt.ylabel("y drift position (m)")
plt.title("y drift vs time")
plt.grid(True)
plt.show()

# ============================================================
# 6. 그래프 3: 시간에 따른 속도
# ============================================================

plt.figure(figsize=(7, 5))
plt.plot(t, v, linewidth=2)
plt.xlabel("time (s)")
plt.ylabel("speed v(t) (m/s)")
plt.title("Speed decreases due to rolling resistance")
plt.grid(True)
plt.show()

# ============================================================
# 7. 그래프 4: 시간에 따른 진행 방향 각도 theta
# ============================================================

plt.figure(figsize=(7, 5))
plt.plot(t, theta, linewidth=2)
plt.xlabel("time (s)")
plt.ylabel("theta (rad)")
plt.title("Direction angle change over time")
plt.grid(True)
plt.show()

# ============================================================
# 8. 애니메이션: 공이 휘어져 움직이는 모습
# ============================================================

fig, ax = plt.subplots(figsize=(7, 5))
ax.set_xlim(np.min(x) - 0.02, np.max(x) + 0.02)
ax.set_ylim(np.min(y) - 0.02, np.max(y) + 0.02)
ax.set_xlabel("x position (m)")
ax.set_ylabel("y drift position (m)")
ax.set_title("Animation of spinning ball drift")
ax.grid(True)
ax.set_aspect("equal", adjustable="box")

trail, = ax.plot([], [], linewidth=2)
ball, = ax.plot([], [], "o", markersize=10)

def init():
    trail.set_data([], [])
    ball.set_data([], [])
    return trail, ball

def update(frame):
    trail.set_data(x[:frame], y[:frame])
    ball.set_data([x[frame]], [y[frame]])
    return trail, ball

ani = FuncAnimation(
    fig,
    update,
    frames=len(t),
    init_func=init,
    interval=20,
    blit=True
)

plt.show()